### PR TITLE
Initial attempt at adding DHCP module

### PR DESCRIPTION
**Pull request by ad8lmondy**
Here is a MVP draft of a DHCP module.

I needed to be able to add very basic DHCP (e.g., just set the range + define domain name) to many VLANs, and this version can do that OK.

However, it is quite a rough draft at the moment - needs more testing, and I'm not entirely convinced it will work with setting DHCP on the lan interface.

Any feedback would be most welcome, I found it a bit of a struggle to work out the paradigm, so I'm sure I've done things a bit weird.

An example task that works:

```
- name: "DHCP for VLAN {{ vlan_id }}"
  pfsense_dhcp:
    state: "{{ present }}"
    enable: yes
    interface: "VLAN{{ vlan_id }}"
    range_from: "10.15.{{ vlan_subnet }}.10"
    range_to: "10.15.{{ vlan_subnet }}.250"
    domain: "vlan{{ vlan_id }}.example.com"
```

### CODE REVIEW

**Comment by chris-cyliu** [comment]
Thank you for your great work. 

I have implemented DHCP and unbound (also other modules like hasync) in my own repo . 

https://github.com/chris-cyliu/ansible-pfsense

Since I dun have time to do the document, I haven't created the pull requests yet. At least I am using them in my lab now.

**Comment by ad8lmondy** [comment]
@chris-cyliu thanks, I've started using your dns module!
I can't seem to raise an issue there, but I've had trouble getting this setting to stick: https://github.com/chris-cyliu/ansible-pfsense/blob/935e757cad29a80f90edfb633fe6cc192b5c3c35/plugins/modules/pfsense_dns.py#L21

Ansible always wants to set it to `""`, but that seems to translate to 'ticked' in the webGUI - how do you set it so that the option is disabled?

**Comment by ad8lmondy** [comment]
@chris-cyliu thanks, I've started using your dns module!
I can't seem to raise an issue there, but I've had trouble getting this setting to stick: https://github.com/chris-cyliu/ansible-pfsense/blob/935e757cad29a80f90edfb633fe6cc192b5c3c35/plugins/modules/pfsense_dns.py#L21

Ansible always wants to set it to `""`, but that seems to translate to 'ticked' in the webGUI - how do you set it so that the option is disabled?

**Comment by chris-cyliu** [comment]
Ops. I didn't test the option `forward_tls_upstream` carefully.

We need to add that attribute to  https://github.com/chris-cyliu/ansible-pfsense/blob/935e757cad29a80f90edfb633fe6cc192b5c3c35/plugins/modules/pfsense_dns.py#L164

Will try to fix it when I have time this week

**Comment by opoplawski** [comment]
@ad8lmondy Do you have time to update this PR?

**Comment by alebeta90** [comment]
what's needed to merge this PR? to rebase with up to date branch?

**Comment by ad8lmondy** [comment]
Apologies, I don't have the time to take this draft PR further.

I believe it requires:
- a review from someone more familar with the pfsensible code base - I was essentially copy+pasting in a debug loop
- more testing - as mentioned, I had it working for my exact use case of particular VLANs, but nothing more.

It might be worth looking at the work done here: https://github.com/pfsensible/core/pull/26#issuecomment-1076422547, as it seemed more robust than what I produced.

**Comment by opoplawski** [comment]
I'm going to close this then.  Perhaps @chris-cyliu could submit some PRs from his work.  Thanks for the contribution, perhaps someone will pick up where you left off.

**Pull request closed without merging**
